name: Generate Snake

on:
  schedule:
    - cron: "*/5 * * * *"     # cada 5 minutos
  workflow_dispatch:         # te permite dispararlo a mano

permissions:
  contents: write            # 🔑 dale permiso de escritura al token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout con credenciales (para poder push)
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # trae todo el historial (necesario para commits)

      # 2) Genera el SVG del snake
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg

      # 3) Commit & push del SVG de vuelta a main
      - name: Commit updated SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update contribution snake"
          file_pattern: github-contribution-grid-snake.svg
          branch: main
