name: Generate Snake

on:
  schedule:
    - cron: "*/5 * * * *" # Cada 5 minutos
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: AlanRosete
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg
